### ISSUE TITLE
xscreensaver enabled

### ISSUE THREAD

**Issue by csmart** [kororaproject/19-beta#1]
In gnome at least, I've had issue where xscreensaver has turned on. we should only be using the desktop's screensaver.

**Comment by firnsy** [comment]
i don't think xscreensaver needs to be installed at all that is add "-xscreensaver-base" to our package list if it's being pulled in or remove the implicit inclusion.

if KDE doesn't use it, i'll yank it from both otherwise just for gnome.

@csmart: does KDE require it?

**Comment by csmart** [comment]
Yeah I looked into this about an hour ago (procrastination) and tested on KDE, which showed without xscreensaver we only get blank, making it the same as GNOME. So I removed xscreensaver from the gnome and kde ks and pushed. I think we can get away with no screensavers in this day and age if you agree.
