### ISSUE TITLE
webapps

### ISSUE THREAD

**Issue by csmart** [kororaproject/19-beta#12]
I did work this out for 17 but didn't ship it cause couldn't ship flash which meant when people used it for things like facebook, no videos, etc.

Now that we ship flash we could re-visit web apps.

The idea is we have an "app" which is actually a web site, but something you can pin to the taskbar and have an application menu entry for.

In GNOME this works by using their browser, but then we should hide it as an application itself as we ship firefox by default.

There may be a better way to do it, maybe should look at how Ubuntu does it.

**Comment by firnsy** [comment]
this is reasonable, best option would be to:
1. add gnome browser,
2. hide the icon via the .desktop, and
3. prevent any "use this as default browser" dialogs

that should be about it

**Comment by csmart** [comment]
what I'm not sure about is making system wide apps, or whether we need to put them in /etc/skel or something. The .deskop that's creates links to a profile with a unique id. You can test this by installing epiphany, browsing to gmail.com and saying "make desktop app" then looking in .local/share/applications/

**Comment by csmart** [comment]
oh, and we need to link up flash to epiphany else it's not worthwhile cause ppl will use this for facebook, etc

The apps to create IMO are gmail and facebook.

Although I notice that gnome now has support for facebook, etc, so maybe we should check out those accounts to see if those do anything that would replace webapps, or if it's just chat, etc.

**Comment by firnsy** [comment]
completely agree, do you want to have a crack at it?

**Comment by csmart** [comment]
I think I'll do this for 20 beta so we get some more testing on it
