### ISSUE TITLE
enable trim by default

### ISSUE THREAD

**Issue by csmart** [kororaproject/19-beta#13]
should we? so we don't need a special mount point any more, just need cronjob to run it against any mount points.

If users have lvm, we need to enable in lvm.conf and if they have luks then need to enable it in crypttab (not sure about enabling it for these latter two).

-c

**Comment by firnsy** [comment]
yup, let's do this

**Comment by csmart** [comment]
Should the script get a list of mounted disk partitions (not tmpfs or vfs), check their device to see if it has TRIM support, then run it on those.

Or just run it on all mounted partitions and if it fails 2>/dev/null?

I'm leaning towards the latter cause if the drive doesn't support trim it will just fail without side effect.

**Comment by csmart** [comment]
Then again, this is untested.. maybe it should go in 20?
