### ISSUE TITLE
gnome 3 shows minimise in window

### ISSUE THREAD

**Issue by csmart** [kororaproject/19-beta#6]
minimise makes no sense in gnome 3 it should not be enabled. We should have maximise and close. This was the default in 18 so not sure what has changed in 19.

**Comment by csmart** [comment]
It should be enabled for gnome classic mode though, where we have a panel

**Comment by firnsy** [comment]
minimise makes perfect sens in gnome 3, it's the first thing i had to enable in k18

**Comment by csmart** [comment]
lol, I didn't know you turned it back on, I thought gnome changed the dconf key.. so taking this discussion to irc

**Comment by csmart** [comment]
OK, closing as we've discussed and changed this.
