### ISSUE TITLE
application titles in gnome are mix of program name and description

### ISSUE THREAD

**Issue by csmart** [kororaproject/19-beta#7]
Under GNOME the applications are sometimes known by their name, e.g. "Brasero" and sometimes by their description "Files" (nautilus).

This is inconsistent and one should be picked over the other and all made to match.

In KDE we use descriptions with names underneath (cause you know, in KDE you can do that sort of thing), but for GNOME it's just very unpolished.

**Comment by firnsy** [comment]
names are defined by Name inside of the repsective .desktop as per the freedesktop standard, not sure how you want to manage this one.

$ grep Name= /usr/share/applications/nautilus.desktop
Name=Files

$ grep Name= /usr/share/applications/brasero.desktop 
Name=Brasero
...

**Comment by csmart** [comment]
Yeah so it looks like most of the apps have their Name set to what they really are, except a few like Nautilus (Files).

Makes sense then to make GNOME use their actual name instead of some random description. Should we change "Files" to be "Nautilus" for consistency? Or just leave it?

All this is all about polish..

We should probably set Jockey yo Jockey rather than "Additional Drivers" though? Although it we replace jockey soon we can probably just leave it.

See "gimp" is called "GNU Image Manipulation Project" which is what gimp stands for.

Miro is called "Miro music and video player".

So, really there are a mix of like 4 types of titles?

**Comment by csmart** [comment]
maybe  "gedit" should be "Gedit" like "Gnote", except the Gnote project actually is "Gnote" whereas the gedit project is actually "gedit".

**Comment by firnsy** [comment]
this can be solved/addressed to the best extent by pinging upstream package maintainer
